### ISSUE TITLE
阿拉伯语可以顺带手搞一个不?

### ISSUE THREAD

**Issue by highwindmx** [Nigh/cjk-romanizer#5]
有点意思哎，不知道阿拉伯语有没有这个可能?

**Comment by Nigh** [comment]
实际的实现是使用 https://github.com/Nigh/transliterate 这个库，将unicode映射到ascii上，实际上是一个map，如果阿拉伯语是一个unicode符号能对应一个ascii的token的话，也是完全可以实现的。
